---
- name: install htpasswd
  apt: name=apache2-utils state=present

- name: htpasswd
  command: htpasswd -bBc /home/austin/htpasswd {{ docker_user }} {{ docker_password }}

- name: setup input rules iptables
  iptables: chain=INPUT destination_port=443 protocol=tcp jump=ACCEPT

- name: start registry
  docker:
    name: registry
    image: registry:2
    state: reloaded
    restart_policy: always
    volumes:
      - /home/austin/certs:/certs
      - /home/austin/htpasswd:/auth/htpasswd
    ports:
      - "{{ ansible_eth0.ipv4.address }}:443:5000"
    env:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
