---
- name: install haproxy
  apt: name=haproxy state=present

- name: create cert chain
  shell: cat fullchain.pem privkey.pem > {{ domain }}.pem chdir=/etc/letsencrypt/live/{{ domain }}

- name: letsencrypt permissions
  file: path=/etc/letsencrypt state=directory recurse=yes mode=0775 group=haproxy

- name: gather facts from webservers
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  with_items: "{{groups['webservers']}}"

- name: haproxy config
  template: src=templates/haproxy.j2 dest=/etc/haproxy/haproxy.cfg

- name: reload haproxy
  service: name=haproxy state=reloaded
