---
- name: install haproxy
  apt: name=haproxy state=present

- name: gather facts from webservers
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  with_items: "{{groups['webservers']}}"

- name: haproxy config
  template: src=templates/haproxy.j2 dest=/etc/haproxy.conf
