version: 2.1
jobs:
  submodule:
    docker:
      - image: austburn/austburn.me:0.0.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:c4TK2coml7ZR1YIZo69AATCeRpXtInXJiMVD/4oH+9k austburn@gmail.com"
      - checkout
      - run:
          name: get submoduled theme
          command: |
            git submodule sync
            git submodule update --init
  test:
    docker:
      - image: austburn/austburn.me:0.0.2
    steps:
      - checkout
      - run: terraform init && terraform plan

workflows:
  main:
    jobs:
      - submodule
      - test:
          requires:
            - submodule

# deployment:
#   master:
#     branch: master
#     commands:
#       - terraform apply
#       - hugo -b "https://austburn.me" --theme=hugo-future-imperfect
#       - aws s3 cp --recursive public s3://blog.austburn.me/
