version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.09
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:1c:d1:0a:fe:bc:31:ea:69:cd:7c:fa:14:8d:f6:ab"
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          command: |
            wget https://github.com/gohugoio/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.deb
            sudo dpkg -i hugo_0.30.2_Linux-64bit.deb
            sudo apt-get install python-pip
            sudo pip install --upgrade awscli
            wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip
            unzip -d "${HOME}/bin" /tmp/terraform.zip

  test:
    docker:
      - image: cimg/base:2020.09
    steps:
      - run: terraform init && terraform plan

  deploy:
    docker:
      - image: cimg/base:2020.09
    steps:
      - run:
          command: |
            terraform apply
            hugo -b "https://austburn.me" --theme=hugo-future-imperfect
            aws s3 cp --recursive public s3://blog.austburn.me/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
