---
- name: configure nginx
  hosts: webservers

  tasks:
    - name: add cert
      template: src=templates/austburn_crt.j2 dest=/etc/ssl/certs/austburn.crt

    - name: add key
      template: src=templates/austburn_key.j2 dest=/etc/ssl/private/austburn.key

    - name: install nginx
      apt: name=nginx state=present

    - name: link nginx config
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: add nginx config
      copy: src=files/austburn.conf dest=/etc/nginx/sites-available/austburn.conf

    - name: link nginx config
      file: src=/etc/nginx/sites-available/austburn.conf dest=/etc/nginx/sites-enabled/austburn.conf state=link

    - name: restart nginx
      service: name=nginx state=restarted
