---
- name: configure nginx
  hosts: webservers
  become: true
  become_user: root

  tasks:
    - name: install bc/git
      apt: name={{ item }} state=present
      with_items:
        - bc
        - git

    - name: rax dns
      lineinfile: dest=/etc/resolv.conf state=present line="nameserver {{ item }}" create=yes
      with_items:
        - dns1.stabletransit.com
        - dns2.stabletransit.com

    - name: grab lets-encrpyt
      git: repo=https://github.com/letsencrypt/letsencrypt dest=/opt/letsencrypt

    - name: grab certs
      command: ./letsencrypt-auto certonly --agree-tos --renew-by-default --email austburn@gmail.com --standalone -d austburn.me chdir=/opt/letsencrypt

    - name: install nginx
      apt: name=nginx state=present

    - name: link nginx config
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: add nginx config
      template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/austburn.conf

    - name: link nginx config
      file: src=/etc/nginx/sites-available/austburn.conf dest=/etc/nginx/sites-enabled/austburn.conf state=link

    - name: restart nginx
      service: name=nginx state=restarted
