---
- name: Install postgres
  hosts: postgres
  gather_facts: true
  become: true
  become_user: root
  tasks:

  roles:
    - { role: ANXS.postgresql , postgresql_listen_addresses: ["{{ ansible_eth2.ipv4.address }}"] }
