---
- name: Install postgres
  hosts: postgres
  become: true
  become_user: root
  vars:
    postgresql_listen_addresses: ["{{ ansible_eth2.ipv4.address }}"]
    postgresql_users:
      - name: "{{ pg_user }}"
        pass: "{{ pg_password }}"
        encrypted: no

  roles:
    - { role: ANXS.postgresql }
