---
- name: start postgres
  become: true
  become_user: austin
  docker:
    name: postgres
    image: postgres
    state: started
    env:
      POSTGRES_USER: "{{ pg_user }}"
      POSTGRES_PASSWORD: "{{ pg_password }}"

- name: start application
  become: true
  become_user: austin
  docker:
    name: austburn-prod
    image: "registry.austburn.me/austburn.app:{{ git_revision }}"
    registry: registry.austburn.me
    username: "{{ docker_user }}"
    password: "{{ docker_password }}"
    state: reloaded
    restart_policy: always
    volumes:
      - /data/application:/application
    links:
      - postgres:postgres
    ports:
      - 127.0.0.1:5050:5050
    expose: 5050
    env:
      POSTGRES_USER: "{{ pg_user }}"
      POSTGRES_PASSWORD: "{{ pg_password }}"
