---
- name: add nginx signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add nginx repos
  lineinfile: dest=/etc/apt/sources.list state=present line="{{ item }}"
  with_items:
    - "deb http://nginx.org/packages/ubuntu/ trusty nginx"
    - "deb-src http://nginx.org/packages/ubuntu/ trusty nginx"

- name: install nginx
  apt: name=nginx=1.10.0-1~trusty update_cache=yes state=present

- name:  remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
